# -*- coding: utf-8 -*-
"""Laboratorio#3 Jarren Chaves

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10wQBwtBjpFVVT9AmA2Hw02Y_CxNlbC-w
"""

import pandas as pd
import matplotlib.pyplot

df = pd.read_csv('/content/CSVInvestigation.csv')
data = pd.DataFrame(df)
print(data)

data = data.astype({"Value":float})
dataFiltered2018 = data.loc[(data)['Year']==2018]
print(dataFiltered2018)

#5 paises con mayor indice de criminalidad
dataFiltered = data.loc[(data['Series']=="Intentional homicide rates per 100,000")]
print(dataFiltered.sort_values(by=['Value'],ascending=False)[['Country','Value']].head(5))

#5 paises con menor indice de criminalidad
print(dataFiltered.sort_values(by=['Value'],ascending=True)[['Country','Value']].head(5))

#El crimen mas repetido por pais para el anno 2018
print(dataFiltered2018['Series'].value_counts())

#Crimen con el porcentaje mas alto en CR en el anno 2005
dataFilteredCR=data.loc[(data['Country']=="Costa Rica")&(data['Year']==2005)]
print(dataFilteredCR)
print(dataFilteredCR.sort_values(by=['Value'],ascending=False)[['Country','Series','Value']])

#Comparativa entre CR, Nicaragua y Panama por medio de la tasa

registro=data.loc[(data["Country"]=="Costa Rica")|(data["Country"]=="Panama")|(data["Country"]=="Nicaragua")]
print(registro)

#Genero que más ha cometido crimenes de homicidio intencional en promedio en el año 2018

print('Genero más afectado en crimenes en promedio en el año 2018')
dataFilteredByGender=dataFiltered2018.loc[((
    dataFiltered2018['Series']=="Percentage of male and female intentional homicide victims, Male")
    |(dataFiltered2018['Series']=="Percentage of male and female intentional homicide victims, Female"))
    ].groupby('Series')['Value']
print(dataFilteredByGender.mean())